SELECT * FROM STUDENT

DROP TABLE STUDENT

CREATE TABLE STUDENT 
(admNo		CHAR(2)	NOT NULL,
NAME		VARCHAR(20)	NOT NULL,
DOB			DATE	NULL,
aggpt		INTEGER	NOT NULL,
gpa			DECIMAL(3,2)  NULL,
PRIMARY KEY (admNo))

--ADD A STUDENT ROW WITH VALUES FOR ALL COLUMNS
INSERT INTO STUDENT
VALUES ('s2', 'mary wong', '04-25-1997', 10, null)

--ADD A STUDENT ROW WITHOUT GPA
INSERT INTO STUDENT (admNo, NAME, DOB, aggpt)
VALUES ('s3', 'tom han', '1997-05-20', 15)

DELETE FROM STUDENT
WHERE admNo = 's1'