-- create a student table

CREATE TABLE STUDENT 
(admNo		CHAR(2)	NOT NULL,
NAME		VARCHAR(20)	NOT NULL,
DOB			DATE	NULL,
aggpt		INTEGER	NOT NULL,
gpa			DECIMAL(3,2)  NOT NULL,
PRIMARY KEY (admNo))

--LIST CONTENTS IN A TABLE

SELECT * FROM STUDENT
